"""Docker containerization for OpenMythos.

Generates Dockerfiles and docker-compose configs for deployment.
"""
import os
from typing import Dict, List, Optional
from dataclasses import dataclass


@dataclass
class DockerBuilder:
    """Build Docker configurations for OpenMythos.
    
    Args:
        model_size: Model variant (1b, 8b, 70b, 1t)
        quantization: Quantization level (fp16, int8, int4)
        gpu: Enable GPU support
    """
    model_size: str = "1b"
    quantization: str = "int4"
    gpu: bool = True
    output_dir: str = "deployment/docker"

    def generate_dockerfile(self) -> str:
        """Generate Dockerfile for OpenMythos inference.
        
        Returns:
            Dockerfile content
        """
        base_image = "nvidia/cuda:12.1.0-runtime-ubuntu22.04" if self.gpu else "python:3.11-slim"
        
        dockerfile = f"""# OpenMythos Inference Server - {self.model_size.upper()} ({self.quantization})
# Generated by OpenMythos Deployment Builder

FROM {base_image}

# System dependencies
RUN apt-get update && apt-get install -y \\
    python3 python3-pip python3-venv \\
    curl wget git \\
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy model and code
COPY open_mythos/ ./open_mythos/
COPY inference/ ./inference/
COPY data/ ./data/
COPY deployment/config.json .

# Environment variables
ENV MODEL_SIZE={self.model_size}
ENV QUANTIZATION={self.quantization}
ENV DEVICE={'cuda' if self.gpu else 'cpu'}
ENV PYTHONUNBUFFERED=1

# Health check
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \\
    CMD curl -f http://localhost:8000/health || exit 1

# Expose ports
EXPOSE 8000

# Run inference server
CMD ["python3", "-m", "inference.api_server", "--host", "0.0.0.0", "--port", "8000"]
"""
        return dockerfile

    def generate_requirements(self) -> str:
        """Generate requirements.txt."""
        reqs = [
            "torch>=2.0.0",
            "transformers>=4.30.0",
            "fastapi>=0.100.0",
            "uvicorn>=0.22.0",
            "pydantic>=2.0.0",
            "sentencepiece>=0.1.99",
            "numpy>=1.24.0",
        ]
        if self.gpu:
            reqs.append("nvidia-ml-py3>=11.525.0")
        return "\n".join(reqs)

    def generate_docker_compose(self, replicas: int = 1) -> str:
        """Generate docker-compose.yml.
        
        Args:
            replicas: Number of service replicas
            
        Returns:
            docker-compose.yml content
        """
        compose = f"""# OpenMythos Docker Compose - {self.model_size.upper()}
version: '3.8'

services:
  openmythos:
    build:
      context: ..
      dockerfile: deployment/docker/Dockerfile
    container_name: openmythos-{self.model_size}
    ports:
      - "8000:8000"
    volumes:
      - model-data:/app/data
    environment:
      - MODEL_SIZE={self.model_size}
      - QUANTIZATION={self.quantization}
      - DEVICE={'cuda' if self.gpu else 'cpu'}
    {'deploy:' if self.gpu else ''}
    {'  resources:' if self.gpu else ''}
    {'    reservations:' if self.gpu else ''}
    {'      devices:' if self.gpu else ''}
    {'        - driver: nvidia' if self.gpu else ''}
    {'          count: 1' if self.gpu else ''}
    {'          capabilities: [gpu]' if self.gpu else ''}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model-data:
"""
        return compose

    def generate_config(self) -> Dict:
        """Generate runtime configuration."""
        return {
            "model": {
                "size": self.model_size,
                "quantization": self.quantization,
                "device": "cuda" if self.gpu else "cpu",
            },
            "server": {
                "host": "0.0.0.0",
                "port": 8000,
                "workers": 1,
                "max_batch_size": 4,
            },
            "finance": {
                "default_domain": "trading",
                "available_domains": ["trading", "business", "cashflow", "indonesian_market", "crypto", "risk"],
            },
        }

    def build(self):
        """Generate all Docker files."""
        os.makedirs(self.output_dir, exist_ok=True)

        with open(os.path.join(self.output_dir, "Dockerfile"), "w") as f:
            f.write(self.generate_dockerfile())

        with open(os.path.join(self.output_dir, "requirements.txt"), "w") as f:
            f.write(self.generate_requirements())

        with open(os.path.join(self.output_dir, "docker-compose.yml"), "w") as f:
            f.write(self.generate_docker_compose())

        import json
        with open(os.path.join(self.output_dir, "config.json"), "w") as f:
            json.dump(self.generate_config(), f, indent=2)

        return self.output_dir
